name: Auto-update EPG

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 04:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-epg:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run EPG cleanup
        shell: pwsh
        run: |
          Write-Host "Running clean_epg.py..."
          python .\clean_epg.py

      - name: Commit and push changes
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add clean_epg.xml
          if ((git status --porcelain) -ne "") {
              git commit -m "Auto-update clean_epg.xml"
              git push
              Write-Host "✅ Changes pushed to GitHub"
          } else {
              Write-Host "No changes detected"
          }
