name: Auto-Update EPG

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 04:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download and clean EPG
        run: |
          python clean_epg.py

      - name: Commit and push updated EPG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add clean_epg.xml
          git commit -m "Auto-update clean EPG"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

