name: Daily Clean EPG Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
